version: 0.0
os: linux
files:
  - source: codedeploy/config/ruby-codedeploy-demo-nginx.conf
    destination: /etc/nginx/conf.d
  - source: codedeploy/config/nginx.conf
    destination: /etc/nginx
permissions:
  - object: /opt/current-deployment
    pattern: "*"
    owner: ec2-user 
    group: ec2-user 
    type:
      - file
hooks:
  BeforeInstall:
    - location: codedeploy/scripts/stop_unicorn.sh
    - location: codedeploy/scripts/configure_nginx.sh
    - location: codedeploy/scripts/install_dependencies.sh
  AfterInstall:
    - location: codedeploy/scripts/start_unicorn.sh
      runas: ec2-user
    - location: codedeploy/scripts/start_nginx.sh
